services:
  postgres:
      image: postgres:15
      env_file:
        - .env
      environment:
        POSTGRES_USER: ${DB_USER_NAME}
        POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_PORT: ${DB_PORT}
      ports:
        - "${DB_PORT}:${DB_PORT}"
      healthcheck:
        test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER_NAME} -d ${DB_NAME}'" ]
        interval: 3s
        timeout: 3s
        retries: 5
      volumes:
        - ./postgres-data:/var/lib/docker/volumes/purple-avito-backend-bruh_misis/_data

  python-fastapi:
      image: auxxxxx/purple-avtio-fastapi-backend:202403092150
      build:
        context:
          .
        dockerfile:
          .Dockerfile
      depends_on:
        postgres:
          condition: service_healthy
      env_file:
        - .env
      environment:
        DATABASE_HOST: postgres
      ports:
        - "${PORT}:${PORT}"
